home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/', views.about, name='about'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('home.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^projects/', include('projects.urls')),
]

projects/urls.py
from django.conf.urls import url
from . import views

app_name = 'projects'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<project_id>[0-9]+)/$', views.project, name='project'),
]

home/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

projects/models.py
from __future__ import unicode_literals
import datetime

from django.db import models
from django.utils import timezone


class Categories(models.Model):
    title = models.CharField(max_length=200)


    def __str__(self):
        return self.title

    #Rewrite plural name of the class in admin panel
    class Meta:
        verbose_name_plural = "categories"


class Projects(models.Model):
    category = models.ForeignKey(Categories, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=2000)
    customer = models.CharField(default="", max_length=200)
    value = models.IntegerField(default=0)
    date_created = models.DateTimeField('date published')

    def __str__(self):
        return self.title

    def created_recently(self):
        return self.date_created >= timezone.now() - datetime.timedelta(days=1)

    # Rewrite plural name of the class in admin panel
    class Meta:
        verbose_name_plural = "projects"

home/views.py
from django.shortcuts import get_object_or_404, render
from projects.models import Projects
from django.http import HttpResponse

def index(request):
    array = Projects.objects.all()
    context = {
        'projects_list': array
    }
    return render(request, 'home/index.html', context)

def about(request):
    return HttpResponse("This is about page")

notes/views.py
from django.shortcuts import render

# Create your views here.

projects/views.py
from django.shortcuts import get_object_or_404, render
from .models import Projects


def index(request):
    array = Projects.objects.all()
    context = {
        'projects_list': array
    }
    return render(request, 'projects/index.html', context)

def project(request, project_id):
    project = get_object_or_404(Projects, id=project_id)
    context = {
        'project': project
    }
    return render(request, 'projects/project-desc.html', context)

proposals/views.py
from django.shortcuts import render

# Create your views here.

reports/views.py
from django.shortcuts import render

# Create your views here.

settings/views.py
from django.shortcuts import render

# Create your views here.

home/templates/home/index.html
<h1>This is a home page</h1>

{% if projects_list %}
<h3>List of projects:</h3>
    <ul>
    {% for project in projects_list %}
        <li><a href="{% url 'projects:project' project.id %}">{{ project.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No projects are available.</p>
{% endif %}

projects/templates/projects/index.html
{% if projects_list %}
    <ul>
    {% for project in projects_list %}
        <li><a href="{% url 'projects:project' project.id %}">{{ project.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No projects are available.</p>
{% endif %}

projects/templates/projects/project-desc.html
{% if project %}
    <h1>Title: {{ project.title }}</h1>
    <p>Description: {{ project.description }}</p>
{% else %}
    <p>No project to display.</p>
{% endif %}